[project]
name = "eightfold-amongus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-auth>=2.0.0",
    "pygame>=2.6.1",
    "requests>=2.32.5",
]
